# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'map_tool_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 824)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabwidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabwidget.sizePolicy().hasHeightForWidth())
        self.tabwidget.setSizePolicy(sizePolicy)
        self.tabwidget.setObjectName("tabwidget")
        self.inputTab = QtWidgets.QWidget()
        self.inputTab.setEnabled(True)
        self.inputTab.setObjectName("inputTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inputTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fileGB = QtWidgets.QGroupBox(self.inputTab)
        self.fileGB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fileGB.sizePolicy().hasHeightForWidth())
        self.fileGB.setSizePolicy(sizePolicy)
        self.fileGB.setMinimumSize(QtCore.QSize(0, 150))
        self.fileGB.setObjectName("fileGB")
        self.gridLayoutWidget = QtWidgets.QWidget(self.fileGB)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 1071, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.browseFileTB2 = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.browseFileTB2.setEnabled(False)
        self.browseFileTB2.setObjectName("browseFileTB2")
        self.gridLayout.addWidget(self.browseFileTB2, 1, 3, 1, 1)
        self.file2LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.file2LE.setEnabled(False)
        self.file2LE.setObjectName("file2LE")
        self.gridLayout.addWidget(self.file2LE, 1, 2, 1, 1)
        self.file1LE = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.file1LE.setObjectName("file1LE")
        self.gridLayout.addWidget(self.file1LE, 0, 2, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setEnabled(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 0, 1, 1)
        self.browseFileTB = QtWidgets.QToolButton(self.gridLayoutWidget)
        self.browseFileTB.setObjectName("browseFileTB")
        self.gridLayout.addWidget(self.browseFileTB, 0, 3, 1, 1)
        self.processPB = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.processPB.setEnabled(False)
        self.processPB.setObjectName("processPB")
        self.gridLayout.addWidget(self.processPB, 2, 3, 1, 1)
        self.delimiterCB = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.delimiterCB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delimiterCB.sizePolicy().hasHeightForWidth())
        self.delimiterCB.setSizePolicy(sizePolicy)
        self.delimiterCB.setMinimumSize(QtCore.QSize(100, 0))
        self.delimiterCB.setObjectName("delimiterCB")
        self.gridLayout.addWidget(self.delimiterCB, 2, 2, 1, 1)
        self.delimiterLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.delimiterLabel.setEnabled(False)
        self.delimiterLabel.setObjectName("delimiterLabel")
        self.gridLayout.addWidget(self.delimiterLabel, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.fileGB)
        self.dataGB = QtWidgets.QGroupBox(self.inputTab)
        self.dataGB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataGB.sizePolicy().hasHeightForWidth())
        self.dataGB.setSizePolicy(sizePolicy)
        self.dataGB.setMinimumSize(QtCore.QSize(0, 350))
        self.dataGB.setObjectName("dataGB")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.dataGB)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 19, 1071, 321))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 2, 1, 1)
        self.key2CB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.key2CB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key2CB.sizePolicy().hasHeightForWidth())
        self.key2CB.setSizePolicy(sizePolicy)
        self.key2CB.setObjectName("key2CB")
        self.gridLayout_2.addWidget(self.key2CB, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.placeTypeCB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.placeTypeCB.setEnabled(False)
        self.placeTypeCB.setObjectName("placeTypeCB")
        self.gridLayout_2.addWidget(self.placeTypeCB, 0, 1, 1, 1)
        self.placeFieldCB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.placeFieldCB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.placeFieldCB.sizePolicy().hasHeightForWidth())
        self.placeFieldCB.setSizePolicy(sizePolicy)
        self.placeFieldCB.setObjectName("placeFieldCB")
        self.gridLayout_2.addWidget(self.placeFieldCB, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.key1CB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.key1CB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.key1CB.sizePolicy().hasHeightForWidth())
        self.key1CB.setSizePolicy(sizePolicy)
        self.key1CB.setObjectName("key1CB")
        self.gridLayout_2.addWidget(self.key1CB, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 5, 1, 1)
        self.stateLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.stateLE.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stateLE.sizePolicy().hasHeightForWidth())
        self.stateLE.setSizePolicy(sizePolicy)
        self.stateLE.setObjectName("stateLE")
        self.gridLayout_2.addWidget(self.stateLE, 0, 6, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 5, 1, 1)
        self.valueCB = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.valueCB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.valueCB.sizePolicy().hasHeightForWidth())
        self.valueCB.setSizePolicy(sizePolicy)
        self.valueCB.setObjectName("valueCB")
        self.gridLayout_2.addWidget(self.valueCB, 2, 6, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.attributesLV = QtWidgets.QListView(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attributesLV.sizePolicy().hasHeightForWidth())
        self.attributesLV.setSizePolicy(sizePolicy)
        self.attributesLV.setMinimumSize(QtCore.QSize(0, 150))
        self.attributesLV.setObjectName("attributesLV")
        self.verticalLayout_5.addWidget(self.attributesLV)
        self.verticalLayout_2.addWidget(self.dataGB)
        self.outputGB = QtWidgets.QGroupBox(self.inputTab)
        self.outputGB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputGB.sizePolicy().hasHeightForWidth())
        self.outputGB.setSizePolicy(sizePolicy)
        self.outputGB.setMinimumSize(QtCore.QSize(0, 120))
        self.outputGB.setObjectName("outputGB")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.outputGB)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 1071, 91))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.htmlFileTB = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.htmlFileTB.sizePolicy().hasHeightForWidth())
        self.htmlFileTB.setSizePolicy(sizePolicy)
        self.htmlFileTB.setObjectName("htmlFileTB")
        self.gridLayout_3.addWidget(self.htmlFileTB, 1, 2, 1, 1)
        self.htmlFileLE = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.htmlFileLE.sizePolicy().hasHeightForWidth())
        self.htmlFileLE.setSizePolicy(sizePolicy)
        self.htmlFileLE.setObjectName("htmlFileLE")
        self.gridLayout_3.addWidget(self.htmlFileLE, 1, 1, 1, 1)
        self.shapefileLE = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapefileLE.sizePolicy().hasHeightForWidth())
        self.shapefileLE.setSizePolicy(sizePolicy)
        self.shapefileLE.setObjectName("shapefileLE")
        self.gridLayout_3.addWidget(self.shapefileLE, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.shapefileTB = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shapefileTB.sizePolicy().hasHeightForWidth())
        self.shapefileTB.setSizePolicy(sizePolicy)
        self.shapefileTB.setObjectName("shapefileTB")
        self.gridLayout_3.addWidget(self.shapefileTB, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.outputGB)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.runPB = QtWidgets.QPushButton(self.inputTab)
        self.runPB.setEnabled(False)
        self.runPB.setObjectName("runPB")
        self.horizontalLayout.addWidget(self.runPB)
        self.cancelPB = QtWidgets.QPushButton(self.inputTab)
        self.cancelPB.setEnabled(True)
        self.cancelPB.setObjectName("cancelPB")
        self.horizontalLayout.addWidget(self.cancelPB)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabwidget.addTab(self.inputTab, "")
        self.mapTab = QtWidgets.QWidget()
        self.mapTab.setEnabled(False)
        self.mapTab.setObjectName("mapTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.mapTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.webView = QtWebEngineWidgets.QWebEngineView(self.mapTab)
        self.webView.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setUrl(QtCore.QUrl("about:blank"))
        self.webView.setObjectName("webView")
        self.verticalLayout_3.addWidget(self.webView)
        self.tabwidget.addTab(self.mapTab, "")
        self.verticalLayout.addWidget(self.tabwidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabwidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Map Generator Tool"))
        self.centralwidget.setToolTip(_translate("MainWindow", "<html><head/><body><p>This tool parses text files containing raw data for U.S. cities, counties, or states; creates a shapefile of the data; and saves and displays the data in a web map.</p></body></html>"))
        self.tabwidget.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.fileGB.setTitle(_translate("MainWindow", "Text Files"))
        self.label.setText(_translate("MainWindow", "File Name:"))
        self.browseFileTB2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to browse for second data file.</p></body></html>"))
        self.browseFileTB2.setText(_translate("MainWindow", "..."))
        self.file2LE.setToolTip(_translate("MainWindow", "<html><head/><body><p>Name of second data text file.</p></body></html>"))
        self.file1LE.setToolTip(_translate("MainWindow", "<html><head/><body><p>Name of the data text file.</p></body></html>"))
        self.checkBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Check the box if there is an additional data file that should be merged with the first file.</p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "Second File:"))
        self.browseFileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to browse for data file.</p></body></html>"))
        self.browseFileTB.setText(_translate("MainWindow", "..."))
        self.processPB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click after selecting data text file(s) and text delimiter to process files.</p></body></html>"))
        self.processPB.setText(_translate("MainWindow", "Process Data"))
        self.delimiterCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the delimiter type for the input text files.</p></body></html>"))
        self.delimiterLabel.setText(_translate("MainWindow", "Delimiter Type:"))
        self.dataGB.setTitle(_translate("MainWindow", "Data "))
        self.label_6.setText(_translate("MainWindow", "Second File Key Field:"))
        self.key2CB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the name of the field in the second file to use as the key to merge with the first file. </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Place Field:"))
        self.label_2.setText(_translate("MainWindow", "Place Type:"))
        self.placeTypeCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the place type for the input text files.</p></body></html>"))
        self.placeFieldCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the field that contains the name of the place (i.e., the field containing the name of the city, county, or state). </p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "First File Key Field:"))
        self.key1CB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the name of the field in the first file to use as the key to merge with the second file. </p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "Enter State:"))
        self.stateLE.setToolTip(_translate("MainWindow", "<html><head/><body><p>If place type is county, enter the name of the state where the counties are located.</p><p><br/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Value Field:"))
        self.valueCB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the field containing values that will be symbolized on the map.</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Output Attribute Fields:"))
        self.attributesLV.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the attribute fields for the output shapefile. Fields specified for Place and Value must be included as attritubes for the tool to run successfully. </p></body></html>"))
        self.outputGB.setTitle(_translate("MainWindow", "Output"))
        self.label_8.setText(_translate("MainWindow", "Shapefile Name:"))
        self.htmlFileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to browse for the folder where the HTML file will be saved.</p></body></html>"))
        self.htmlFileTB.setText(_translate("MainWindow", "..."))
        self.htmlFileLE.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the name of the output HTML file.</p></body></html>"))
        self.shapefileLE.setToolTip(_translate("MainWindow", "<html><head/><body><p>Select the name of the output shapefile.</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "HTML File Name:"))
        self.shapefileTB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to browse for the folder where the shapefile will be saved.</p></body></html>"))
        self.shapefileTB.setText(_translate("MainWindow", "..."))
        self.runPB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to run the tool.</p></body></html>"))
        self.runPB.setText(_translate("MainWindow", "Run Tool"))
        self.cancelPB.setToolTip(_translate("MainWindow", "<html><head/><body><p>Click to exit this application.</p></body></html>"))
        self.cancelPB.setText(_translate("MainWindow", "Cancel"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.inputTab), _translate("MainWindow", "Input"))
        self.tabwidget.setTabText(self.tabwidget.indexOf(self.mapTab), _translate("MainWindow", "Map"))

from PyQt5 import QtWebEngineWidgets
